#!/bin/bash
set -o errexit

make distclean

docker create -ti --name=phob-tmp phob:latest true >/dev/null

for file in \
	Makefile \
	libtool \
  ext/fileinfo/libmagic/config.h \
  ext/bcmath/libbcmath/src/config.h \
  ext/mbstring/libmbfl/config.h \
  ext/pcre/pcre2lib/config.h \
	sapi/fpm/fpm/fpm_config.h \
	main/php_config.h \
	Zend/zend_config.h \
	ext/opcache/jit/vtune/ittnotify_config.h \
	ext/date/lib/timelib_config.h \
	main/build-defs.h \
	ext/opcache/minilua \
	main/internal_functions_cli.c
do
  [[ -f $file ]] && [[ -z $CLOBBER ]] && continue
	echo $file
	docker cp phob-tmp:/build/phob/$file $(dirname $file)
done

docker rm -f phob-tmp >/dev/null

docker run --mount type=bind,source=$(pwd),target=/build/phob phob make clean

mkdir -p /tmp/build/phob/ccache

docker run \
  --mount type=bind,source=$(pwd),target=/build/phob \
  --mount type=bind,source=/tmp/build/phob/ccache,target=/tmp/ccache \
  phob sh -c 'CCACHE_DIR=/tmp/ccache make -j$(nproc)'

[[ -z $RUN_TESTS ]] && exit 0
sed -i "s/run-tests.php -n -c/run-tests.php -j\$\$(nproc) -n -c/" Makefile
docker run --mount type=bind,source=$(pwd),target=/build/phob phob make test


