#!/bin/sh
set -o errexit

export NPROCS=$(nproc 2>/dev/null || echo 1)
export CC='ccache clang'
export CXX='ccache clang'
export LD='ld.lld'
export NO_INTERACTION=1

#make clean
#make -j$NPROCS
#make test
#exit 0

################

./buildconf
./configure --prefix=/opt/phob \
	--with-pic \
	--enable-fpm \
	--enable-phpdbg \
	--enable-debug \
	--enable-debug-assertions \
	--with-openssl \
	--with-kerberos \
	--with-system-ciphers \
	--with-external-pcre \
	--with-pcre-jit \
	--with-zlib \
	--enable-bcmath \
	--with-bz2 \
	--enable-calendar \
	--with-curl \
	--with-ffi \
	--enable-ftp \
	--enable-gd \
	--with-external-gd \
	--with-gettext \
	--with-gmp \
	--enable-intl \
	--with-ldap \
	--with-ldap-sasl \
	--enable-mbstring \
	--with-mysqli \
	--with-pdo-mysql \
	--with-pdo-pgsql \
	--with-pdo-sqlite \
	--with-pgsql \
	--with-readline \
	--enable-shmop \
	--enable-sockets \
	--with-sodium \
	--with-password-argon2 \
	--enable-sysvmsg \
	--enable-sysvsem \
	--enable-sysvshm \
	--with-zip \
	--enable-mysqlnd

make -j$NPROCS

sed -i "s/run-tests.php -n -c/run-tests.php -j$NPROCS -n -c/" Makefile
make test


