#!/bin/sh

set -o errexit

export NPROCS=$(nproc 2>/dev/null || echo 1)
export CC='ccache clang'
export CXX='ccache clang'
export NO_INTERACTION=1

make distclean 2>/dev/null || true

./buildconf

./configure --prefix=/opt/phob

sed -i "s/run-tests.php -n -c/run-tests.php -j$NPROCS -n -c/" Makefile

make -j$NPROCS
make test


